spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
server:
  port: 8080
  ssl:
    key-store-type: PKCS12
    key-store: classpath:certificado.p12
    key-store-password: Toletole12#
    key-alias: nicotole
    enabled: true