server:
  port: 8100

spring:
  application:
    name: models
  datasource:
    url: jdbc:mysql://200.45.208.91:3306/vps3_sandbox?serverTimezone=UTC
    username: vps3_sand
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

cloud:
  discovery:
    client:
      service-url:
        defaultZone: http://200.45.208.91:8761
