server:
  port: 6000

spring:
  application:
    name: persistence
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

cloud:
  discovery:
    client:
      service-url:
        defaultZone: ${SERVER}
